version: "3.3"

services:
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/hepsikafka"
    environment:
      - KAFKA_ENABLE_KRAFT=yes #Whether to enable Kafka Raft (KRaft) mode. Without zookeper
      - KAFKA_CFG_PROCESS_ROLES=broker,controller #kafka config controller.listener.names The roles that this process plays: 'broker', 'controller', or 'broker,controller' if it is both. This configuration is only applicable for clusters in KRaft
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER #kafka config listener.names.controller only for kraft mode
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT #her listenerın security protcol olarak neyle iletisim kuracagi
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9094,CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://127.0.0.1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT #Name of listener used for communication between brokers
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9094 #birden fazla controller broker olabilir bu property ile onları gosteririz Eger  controller ozerlligine sahip 2 id'li bir broker daha olsaydı 2@x.x.x.x:9094 gibi tanımlardık
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
volumes:
  kafka_data:
    driver: local