version: "3.3"

services:

  kafka0:
    image: confluentinc/cp-kafka:latest
    hostname: kafka0
    container_name: kafka0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://:9094,CLIENT://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka0:9093,EXTERNAL://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:9094,2@kafka1:9097'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./command-input-files/reassign-topic-1-a.json:/tmp/reassign-topic-1-a.json
      - ./command-input-files/reassign-topic-1-b.json:/tmp/reassign-topic-1-b.json
      - ./command-input-files/reassign-topic-2-a.json:/tmp/reassign-topic-2-a.json
      - ./command-input-files/reassign-topic-2-b.json:/tmp/reassign-topic-2-b.json
      - ./scripts/update_run.sh:/tmp/update_run.sh
      - ./clusterID2:/tmp/clusterID
    command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9095:9095"
    environment:
      KAFKA_LISTENERS: CONTROLLER://:9097,CLIENT://:9096,EXTERNAL://:9095
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka1:9096,EXTERNAL://127.0.0.1:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:9094,2@kafka1:9097'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./command-input-files/reassign-topic-1-a.json:/tmp/reassign-topic-1-a.json
      - ./command-input-files/reassign-topic-1-b.json:/tmp/reassign-topic-1-b.json
      - ./command-input-files/reassign-topic-2-a.json:/tmp/reassign-topic-2-a.json
      - ./command-input-files/reassign-topic-2-b.json:/tmp/reassign-topic-2-b.json
      - ./scripts/update_run.sh:/tmp/update_run.sh
      - ./clusterID2:/tmp/clusterID
    command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka0:9093
      - KAFKA_CLUSTERS_1_NAME=secondLocal
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=kafka1:9096